import {SubjectsModel} from "./subjectsmodel";
import {LMSModel} from "./lmsmodel";
import {Validator} from "./validator";
import {TeachersModel} from "./teachersmodel";
import {PupilsModel} from "./pupilsmodel";
import {GroupsModel} from "./groupsmodel";
import {GradeBooksModel} from "./gradebooksmodel";
export {SubjectsModel};
export {LMSModel};
export {TeachersModel};
export {Validator};
export {PupilsModel};
export {GroupsModel};
export {GradeBooksModel};