import {SubjectsModel} from "./subjectsmodel";
import {LMSModel} from "./lmsmodel";
// import {TeachersModel} from "./teachersmodel";
// import {PupilsModel} from "./pupilsmodel";
// import {GroupsModel} from "./groupsmodel";
// import {GradebooksModel} from "./gradebooksmodel";
export {SubjectsModel};
export {LMSModel};
// export {TeachersModel};
// export {PupilsModel};
// export {GroupsModel};
// export {GradebooksModel};